name: publish-and-tag

on:
  workflow_call:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: 3.6

    - name: Install poetry
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Install dependencies
      shell: bash
      run: poetry install

    - name: Publish package to pypi
      shell: bash
      run: poetry publish --build -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASS }}

    - name: Tag commit
      if: github.ref_name == 'main'
      uses: mt-actions/tag-commit@v1.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
